### ISSUE TITLE
"undefined symbol luaopen_string"

### ISSUE THREAD

**Issue by ThaCuber** [TorchedSammy/Evergreen.lxl#38]
this is probably not related to the plugin at all, but I tried installing it using [lpm](https://github.com/lite-xl/lite-xl-plugin-manager) (I also installed ltreesitter using the command written in the README.md) and I get this error:
```
Sat Jun 17 13:36:37 2023 [ERROR] Failed loading /home/thacuber2a03/.luarocks/lib/lua/5.4/ltreesitter.so: /home/thacuber2a03/.luarocks/lib/lua/5.4/ltreesitter.so: undefined symbol: lua_checkstack at /home/thacuber2a03/.local/bin/lite-xl/data/core/init.lua:1226

stack traceback:
[C]: in function 'system.load_native_plugin'
[C]: in function 'require'
...hacuber2a03/.config/lite-xl/plugins/evergreen/parser.lua:2: in main chunk
[C]: in function 'require'
.../thacuber2a03/.config/lite-xl/plugins/evergreen/init.lua:21: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
/home/thacuber2a03/.local/bin/lite-xl/data/core/init.lua:1225: in function 'core.try'
/home/thacuber2a03/.local/bin/lite-xl/data/core/init.lua:1013: in function 'core.load_plugins'
/home/thacuber2a03/.local/bin/lite-xl/data/core/init.lua:793: in function 'core.init'
[string "local core..."]:8: in function <[string "local core..."]:2>
[C]: in function 'xpcall'
[string "local core..."]:2: in main chunk
```
no idea why does this happen nor do I think I can solve it
if this isn't related to the plugin then can someone please point me to where I should go?

**Comment by takase1121** [comment]
We've found the problem that caused the issue. Evergreen.lxl uses ltreesitter, compiled for Lua. Since Lua is statically linked to lite-xl, no actions has been taken to ensure that all Lua symbols are exported. Now, the "proper" way to "fix" this is to modify the plugin to use the lite-xl plugin API, but v2.1.0 has a bug where `lua_rotate` is not exported via the API.

To fix this, you need `master` from lite-xl and modify ltreesitter to use the API. I have some work to do this, but I haven't uploaded it yet.
